"""add city zipcode

Revision ID: 53137c961d70
Revises: b27899fe8a49
Create Date: 2022-02-23 19:36:40.427495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53137c961d70'
down_revision = 'b27899fe8a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('cit_zipcode', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_city_cit_zipcode'), 'city', ['cit_zipcode'], unique=False)
    op.execute("UPDATE city SET cit_zipcode=''")

    # use batch operation for sqlite compatibility
    # otherwise code could be replace by the line below
    # op.alter_column('city', 'cit_zipcode', nullable=False)
    with op.batch_alter_table('city') as batch_op:
        batch_op.alter_column('cit_zipcode', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_cit_zipcode'), table_name='city')
    op.drop_column('city', 'cit_zipcode')
    # ### end Alembic commands ###
