"""Add score cascade deletion

Revision ID: 87a91e6d361d
Revises: 53137c961d70
Create Date: 2022-02-28 09:14:56.840885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a91e6d361d'
down_revision = '53137c961d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint(
            constraint_name='score_sco_idcity_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            constraint_name='fk_score_city',
            referent_table='city',
            local_cols=['sco_idcity'],
            remote_cols=['cit_id'],
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint(
            constraint_name='fk_score_city', type_='foreignkey')
        batch_op.create_foreign_key(
            constraint_name='score_sco_idcity_fkey',
            referent_table='city',
            local_cols=['sco_idcity'],
            remote_cols=['cit_id']
        )
    # ### end Alembic commands ###
