"""initial schema

Revision ID: b27899fe8a49
Revises: 
Create Date: 2022-02-23 11:03:29.087830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27899fe8a49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('cit_id', sa.Integer(), nullable=False),
    sa.Column('cit_name', sa.String(length=300), nullable=False),
    sa.Column('cit_codeinsee', sa.String(length=300), nullable=False),
    sa.Column('cit_lat', sa.Float(), nullable=True),
    sa.Column('cit_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cit_id'),
    sa.UniqueConstraint('cit_name', 'cit_codeinsee', name='ux_cit_name_codeinsee')
    )
    op.create_index(op.f('ix_city_cit_codeinsee'), 'city', ['cit_codeinsee'], unique=False)
    op.create_index(op.f('ix_city_cit_name'), 'city', ['cit_name'], unique=False)
    op.create_table('score',
    sa.Column('sco_id', sa.Integer(), nullable=False),
    sa.Column('sco_idcity', sa.Integer(), nullable=False),
    sa.Column('sco_year', sa.Integer(), nullable=False),
    sa.Column('sco_airquality', sa.Float(), nullable=True),
    sa.Column('sco_waterpollution', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(columns=['sco_idcity'], refcolumns=['city.cit_id'], name='score_sco_idcity_fkey'),
    sa.PrimaryKeyConstraint('sco_id'),
    sa.UniqueConstraint('sco_idcity', 'sco_year', name='ix_sco_year_idcity')
    )
    op.create_index(op.f('ix_score_sco_idcity'), 'score', ['sco_idcity'], unique=False)
    op.create_index(op.f('ix_score_sco_year'), 'score', ['sco_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_sco_year'), table_name='score')
    op.drop_index(op.f('ix_score_sco_idcity'), table_name='score')
    op.drop_table('score')
    op.drop_index(op.f('ix_city_cit_name'), table_name='city')
    op.drop_index(op.f('ix_city_cit_codeinsee'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
