version: '3.2'

services:
  authent:
    image: quay.io/keycloak/keycloak:16.1.1
    restart: "no"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER:-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD:-admin}
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - "${KEYCLOACK_PORT:-8081}:8080"
    volumes:
      - cityscore-idp:/opt/jboss/keycloak/standalone/data
      - ./keycloack/realm-export.json:/tmp/realm-export.json
  db:
    image: postgres:13.4-alpine
    restart: "no"
    environment:
      - POSTGRES_DB=${PG_DB:-postgres}
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-postgres}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - cityscore-db:/var/lib/postgresql/data
  back:
    image: ${BACKEND_IMG:-cityscore/webapi:local}
    restart: "no"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_DB=${PG_DB:-postgres}
      - POSTGRES_PORT=${PG_PORT:-5432}
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-postgres}
      - KEYCLOACK_URL=http://authent:8080/auth/
      - KEYCLOACK_REALM=${KEYCLOACK_REALM:-cityscore}
      - KEYCLOACK_CLIENT_ID=${KEYCLOACK_CLIENT_ID:-back}
      - KEYCLOACK_ADMIN_ROLE=${KEYCLOACK_ADMIN_ROLE:-api_admin}
      - CREATE_DATASET=${CREATE_DATASET:-True}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - authent

volumes:
  cityscore-idp:
  cityscore-db:
